// <auto-generated />
using System;
using Manajemen_Pro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Manajemen_Pro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Manajemen_Pro.Models.Produk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Harga")
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Produk");
                });

            modelBuilder.Entity("Manajemen_Pro.Models.Transaksi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Jumlah")
                        .HasColumnType("int");

                    b.Property<string>("NamaPelanggan")
                        .HasColumnType("longtext");

                    b.Property<int>("ProdukId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("TotalHarga")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ProdukId");

                    b.ToTable("Transaksi");
                });

            modelBuilder.Entity("Manajemen_Pro.Models.Transaksi", b =>
                {
                    b.HasOne("Manajemen_Pro.Models.Produk", "Produk")
                        .WithMany("Transaksis")
                        .HasForeignKey("ProdukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produk");
                });

            modelBuilder.Entity("Manajemen_Pro.Models.Produk", b =>
                {
                    b.Navigation("Transaksis");
                });
#pragma warning restore 612, 618
        }
    }
}
